dethcrypto/TypeChain

.gitignore, .npmignore, .travis.yml, README.md, package.json, scripts/test.sh, test/contracts/Dumbcontract.sol, test/integration/DumbContract.spec.ts, test/integration/utils/web3Contracts.ts, test/integration/web3.ts, tsconfig.json, typings/ganache-cli.d.ts, yarn.lock
- adds example contracts
- adds basic integration test
=> Integration tests

README.md, lib/cli.ts, lib/parseArgs.ts, package.json, typings/json.ts, yarn.lock
- custom globs
- option to overwrite files
=> Cli revamp

.gitignore, .npmignore, README.md, lib/cli.ts, lib/parseArgs.ts, package.json, scripts/test.sh, test/integration/outDir.spec.ts
=> Add support for outDir option

lib/generateSource.ts
=> improve check for empty contract

README.md, lib/abiParser.ts, lib/cli.ts, lib/generateTypeChainWrappers.ts, lib/logger.ts, lib/parseArgs.ts, package.json, scripts/generate.ts
Related: https://github.com/Neufund/TypeChain/issues/61
=> export API, refactor logger

runtime/typechain-runtime.ts, scripts/test.sh, test/integration/DumbContract.spec.ts
Closes https://github.com/krzkaczor/TypeChain/issues/78
=> fix noUnusedParameters compliance, add noUnusedParameters compiler flag

lib/targets/web3/generation.ts
We should be able to pass null in topics, otherwise we cannot skip some topic. This is important because topics are order-dependent.
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
Btw thanks for this amazing tool!
=> Fix topics types

lib/targets/web3/generation.ts, test/integration/targets/web3-1.0.0/DumbContract.spec.web3.ts
closes https://github.com/ethereum-ts/TypeChain/issues/132
=> add clone method to web3 target

__snapshots__/DumbContract.spec.ts.js, lib/targets/ethers/generation.ts, test/integration/contracts/DumbContract.sol, test/integration/targets/ethers/DumbContract.spec.ts
=> Output type is "number" instead of "BigNumber" when bits <= 48

lib/targets/web3/generation.ts
=> correct a typing of web3 generator

CHANGELOG.md, README.md
=> fix readme note about web3 typings

__snapshots__/DumbContract.spec.ts.js, lib/parser/parseEvmType.spec.ts, lib/parser/typeParser.ts, lib/targets/ethers/generation.ts, lib/targets/legacy/generation.ts, lib/targets/truffle/generation.ts, lib/targets/web3/generation.ts, test/integration/contracts/DumbContract.sol, test/integration/targets/web3-1.0.0/DumbContract.spec.web3.ts
=> Add DynamicBytesType evm type for bytes type

lib/targets/ethers/generation.ts
This fixes issue https://github.com/ethereum-ts/TypeChain/issues/168
=> Constructor types where Arrayish and BigNumberish are in an array or struct

README.md
I assumed that they should be pointed to the local paths in the repo.
=> docs: fix broken links under "Packages" section

packages/target-ethers-v5-test/types/DataTypesInput.d.ts, packages/target-ethers-v5-test/types/DataTypesPure.d.ts, packages/target-ethers-v5-test/types/DataTypesView.d.ts, packages/target-ethers-v5-test/types/Events.d.ts, packages/target-ethers-v5-test/types/NameMangling.d.ts, packages/target-ethers-v5-test/types/Overloads.d.ts, packages/target-ethers-v5-test/types/Payable.d.ts, packages/target-ethers-v5/src/codegen/index.ts
Based on ethers-io/ethers.js#924
=> Update staticCall to callStatic in ethers v5 target

.circleci/config.yml, package.json, packages/target-ethers-v5-test/types/Events.d.ts, packages/target-ethers-v5-test/types/Payable.d.ts
Fixes: https://github.com/ethereum-ts/TypeChain/pull/258#issuecomment-660537576
=> Ensure no git changes

packages/target-ethers-v5-test/types/DataTypesInput.d.ts, packages/target-ethers-v5-test/types/DataTypesPure.d.ts, packages/target-ethers-v5-test/types/DataTypesView.d.ts, packages/target-ethers-v5/src/codegen/types.ts
=> Support fixed length arrays

CONTRIBUTING.md, packages/typechain/package.json
Closes https://github.com/ethereum-ts/TypeChain/issues/283
=> Make new release

examples/ethers-v5/package.json, examples/ethers-v5/src/index.ts, examples/ethers-v5/tsconfig.json, examples/ethers-v5/yarn.lock
Hi there. 
I updated the `ethers-v5` example. Let me know what you would like changed, and I'll update it.
Cheers
=> Update "ethers-v5" example

examples/ethers-v5/package.json, examples/ethers-v5/src/index.ts, examples/ethers-v5/tsconfig.json, examples/ethers-v5/yarn.lock, packages/target-ethers-v4-test/package.json, packages/target-ethers-v4/package.json, packages/target-ethers-v5-test/package.json, packages/target-ethers-v5/package.json, packages/target-truffle-v4-test/package.json, packages/target-truffle-v5-test/package.json, packages/target-web3-v1-test/package.json, packages/target-web3-v1/package.json
Blocked by: https://github.com/ethereum-ts/TypeChain/pull/291
=> Bump ethers 

packages/target-ethers-v4/src/codegen/index.ts
=> Corrected module path for ethers-4 generated factories

.changeset/fair-paws-pay.md, .changeset/silver-crabs-report.md, packages/target-ethers-v4-test/test/DataTypesInput.test.ts, packages/target-ethers-v4-test/types/DataTypesInput.d.ts, packages/target-ethers-v4-test/types/DataTypesPure.d.ts, packages/target-ethers-v4-test/types/DataTypesView.d.ts, packages/target-ethers-v4/src/codegen/types.ts, packages/target-ethers-v5-test/test/DataTypesInput.test.ts, packages/target-ethers-v5-test/test/Overload.test.ts, packages/target-ethers-v5-test/types/DataTypesInput.d.ts, packages/target-ethers-v5-test/types/DataTypesPure.d.ts, packages/target-ethers-v5-test/types/DataTypesView.d.ts, packages/target-ethers-v5-test/types/Library.d.ts, packages/target-ethers-v5-test/types/LibraryConsumer.d.ts, packages/target-ethers-v5-test/types/NameMangling.d.ts, packages/target-ethers-v5-test/types/Overloads.d.ts, packages/target-ethers-v5/src/codegen/types.ts, packages/target-truffle-v5-test/test/DataTypesView.test.ts, packages/target-truffle-v5-test/types/truffle-contracts/DataTypesInput.d.ts, packages/target-truffle-v5-test/types/truffle-contracts/DataTypesPure.d.ts, packages/target-truffle-v5-test/types/truffle-contracts/DataTypesView.d.ts, packages/target-truffle-v5/src/codegen/types.ts, packages/test-utils/package.json, packages/test-utils/src/index.ts, packages/typechain/package.json, yarn.lock
Closes: https://github.com/ethereum-ts/TypeChain/issues/232
=> Improve types for tuples

packages/target-truffle-v5-test/types/truffle-contracts/types.d.ts, packages/target-truffle-v5/package.json, packages/target-truffle-v5/static/types.d.ts, yarn.lock
=> Issues/315 truffle-v5: Some properties of `Truffle.ContractInstance` are missing

packages/target-ethers-v4-test/types/DataTypesInput.d.ts, packages/target-ethers-v5-test/types/DataTypesInput.d.ts, packages/typechain/src/utils/signatures.ts, packages/typechain/test/utils/signatures.test.ts
=> Fix signature of overloaded methods with struct in arguments

.changeset/twelve-comics-bow.md, packages/target-web3-v1-test/types/types.d.ts, packages/target-web3-v1/static/types.d.ts
as per the docs:
https://web3js.readthedocs.io/en/v1.3.0/web3-eth.html#call
=> [web3] add support for passing optional block number to call functions

examples/ethers-v5/package.json, examples/ethers-v5/src/index.ts, examples/ethers-v5/yarn.lock
Updates dependencies, and the new factory class name.
=> Update ethers-v5 example

packages/target-ethers-v5-test/types/commons.ts, packages/target-ethers-v5/src/index.ts
=> Fix unused type parameters ts error

.changeset/sour-files-compare.md, packages/hardhat/src/index.ts
Moved: https://github.com/rhlsthrm/hardhat-typechain/pull/16
=> Accept underscores in contract names

.changeset/beige-jobs-search.md, .prettierignore, contracts/Events.sol, packages/target-ethers-v4-test/types/Events.d.ts, packages/target-ethers-v4-test/types/factories/Events__factory.ts, packages/target-ethers-v5-test/types/Events.d.ts, packages/target-ethers-v5-test/types/factories/Events__factory.ts, packages/target-ethers-v5/src/codegen/index.ts, packages/target-ethers-v5/src/codegen/types.ts, packages/target-truffle-v4-test/types/truffle-contracts/Events.d.ts, packages/target-truffle-v5-test/types/truffle-contracts/Events.d.ts, packages/target-web3-v1-test/types/Events.d.ts
Closes: https://github.com/ethereum-ts/TypeChain/issues/353
=> Fix code generation for events with tuples

.changeset/silly-laws-listen.md, packages/target-ethers-v5-test/types/factories/DataTypesInput__factory.ts, packages/target-ethers-v5-test/types/factories/DataTypesPure__factory.ts, packages/target-ethers-v5-test/types/factories/DataTypesView__factory.ts, packages/target-ethers-v5-test/types/factories/Events__factory.ts, packages/target-ethers-v5-test/types/factories/LibraryConsumer__factory.ts, packages/target-ethers-v5-test/types/factories/Library__factory.ts, packages/target-ethers-v5-test/types/factories/NameMangling__factory.ts, packages/target-ethers-v5-test/types/factories/Overloads__factory.ts, packages/target-ethers-v5-test/types/factories/PayableFactory__factory.ts, packages/target-ethers-v5-test/types/factories/Payable__factory.ts, packages/target-ethers-v5/src/codegen/index.ts
Addresses https://github.com/ethereum-ts/TypeChain/issues/344.
=> Expose ABI, bytecode, and Interface as static factory members

.changeset/nasty-games-notice.md, .changeset/thick-buckets-give.md, packages/hardhat/src/index.ts, packages/hardhat/src/types.ts
Closes: https://github.com/ethereum-ts/TypeChain/issues/377
Closes: https://github.com/ethereum-ts/TypeChain/issues/377
=> Fix bug in incremental generation for target that doesn't support it

packages/hardhat/README.md
https://github.com/ethereum-ts/TypeChain/issues/390
=> update README with hardhat@2.3.0

.changeset/rude-plants-call.md, packages/hardhat/src/constants.ts, packages/hardhat/src/index.ts
Ref: https://github.com/ethereum-ts/TypeChain/pull/417
=> feat: define TASK_TYPECHAIN constant

packages/typechain/src/parser/abiParser.ts
=> Fixed library linking using linkReferences for hardhat artifacts

.changeset/funny-eagles-judge.md, packages/hardhat/src/index.ts, packages/hardhat/test/project.test.ts
Closes: https://github.com/ethereum-ts/TypeChain/issues/431
=> Fix cwd selection in hardhat projects

.changeset/clean-cougars-hang.md, packages/hardhat/test/fixture-projects/hardhat-project/typechain/hardhat.d.ts, packages/target-ethers-v5/src/codegen/hardhat.ts
=> [ethers-v5] Add support for getContractAt

.changeset/sweet-ducks-doubt.md, contracts/v0.6.4/DataTypesInput.sol, packages/target-ethers-v4-test/types/DataTypesInput.d.ts, packages/target-ethers-v4-test/types/factories/DataTypesInput__factory.ts, packages/target-ethers-v5-test/test/DataTypesInput.test.ts, packages/target-ethers-v5-test/types/DataTypesInput.ts, packages/target-ethers-v5-test/types/factories/DataTypesInput__factory.ts, packages/target-ethers-v5/src/codegen/types.ts, packages/target-truffle-v5-test/types/truffle-contracts/DataTypesInput.d.ts, packages/target-web3-v1-test/types/DataTypesInput.ts
=> [ethers-v5] fix structs generated as arrays

packages/target-ethers-v5/src/codegen/index.ts
This PR attempts to tighten up the import lists and avoid importing things that won't be used in the type file. Fixes the issue mentioned here: https://github.com/dethcrypto/TypeChain/issues/430#issuecomment-964314162
Not super happy with the code, but it works. Let me know if there's anything that I need to change.
=> Exclude unused imports from being added to the type file

.changeset/fluffy-singers-visit.md, contracts/v0.6.4/Events.sol, contracts/v0.8.9/Issue552_Reproduction.sol, packages/target-ethers-v4-test/types/Events.d.ts, packages/target-ethers-v4-test/types/factories/Events__factory.ts, packages/target-ethers-v4/src/codegen/index.ts, packages/target-ethers-v5-test/types/Events.ts, packages/target-ethers-v5-test/types/factories/Events__factory.ts, packages/target-ethers-v5/src/codegen/events.ts, packages/target-ethers-v5/test/generation.test.ts, packages/target-truffle-v5-test/types/truffle-contracts/Events.d.ts, packages/target-web3-v1-test/types/Events.ts
Closes https://github.com/dethcrypto/TypeChain/issues/575
=> Add missing parameter names to event filter

.github/workflows/ci.yml, .github/workflows/release.yml
=> Use builtin cache

.changeset/thirty-spoons-smile.md, contracts/v0.6.4/DataTypesInput.sol, packages/target-ethers-v5-test/test/DataTypesInput.test.ts, packages/target-ethers-v5-test/types/factories/v0.6.4/DataTypesInput__factory.ts, packages/target-ethers-v5-test/types/v0.6.4/DataTypesInput.ts, packages/target-ethers-v5/src/codegen/types.ts, packages/target-ethers-v5/test/structs.test.ts, packages/target-truffle-v5-test/types/truffle-contracts/DataTypesInput.d.ts, packages/target-web3-v1-test/types/v0.6.4/DataTypesInput.ts, packages/typechain/src/parser/abiParser.ts, packages/typechain/src/parser/parseEvmType.ts, packages/typechain/test/parser/abiParser.test.ts, packages/typechain/test/parser/parseEvmType.test.ts
EDIT by Kris: 
Tracked via: DET-40
#605
=> Fix ethers v5 target incorrect type generated for struct array array

packages/target-ethers-v5-test/test/DataTypesInput.test.ts, packages/target-ethers-v5-test/test/Events.test.ts, packages/target-ethers-v5-test/test/Issue552Reproduction.test.ts, packages/target-ethers-v5-test/test/Overload.test.ts, packages/target-ethers-v5-test/test/common.ts, packages/target-web3-v1-test/test/DataTypesInput.test.ts, packages/target-web3-v1-test/test/DataTypesPure.test.ts, packages/target-web3-v1-test/test/DataTypesView.test.ts, packages/target-web3-v1-test/test/Events.test.ts, packages/target-web3-v1-test/test/Overload.test.ts, packages/target-web3-v1-test/test/Payable.test.ts, packages/target-web3-v1-test/test/common.ts
=> Change createNewBlockchain in ethers-v5 tests

packages/target-ethers-v5/test/typescript-version.test.ts
=> fix version check test

.changeset/wet-turtles-type.md, packages/typechain/src/parser/abiParser.ts, packages/typechain/test/parser/abiParser.test.ts
Closes https://github.com/dethcrypto/TypeChain/issues/638
=> Prevent abiParser from breaking too easily

.changeset/wild-bags-attack.md, packages/hardhat/src/types.ts, packages/target-ethers-v5/src/codegen/index.ts, packages/typechain/src/typechain/runTypeChain.ts
=> #692/discriminate fixes

.changeset/five-onions-notice.md, examples/hardhat-truffe-v5/package.json, examples/hardhat/package.json, packages/hardhat-test/package.json, packages/hardhat/README.md, packages/hardhat/package.json, packages/hardhat/src/config.ts, packages/hardhat/src/index.ts, packages/hardhat/src/types.ts, packages/hardhat/test/fixture-projects/no-override-project/contracts/c.sol, packages/hardhat/test/fixture-projects/no-override-project/hardhat.config.ts, packages/hardhat/test/project.test.ts, pnpm-lock.yaml
https://github.com/dethcrypto/TypeChain/pull/713
=> Add `dontOverrideCompile` setting and fix a bug

.changeset/bright-roses-bathe.md, packages/hardhat/README.md, packages/hardhat/src/config.ts
=> Don't autodisable overrides for js projects

README.md
per deprecation notice posted at pre-PR link target.
=> Update link to example

.changeset/ethers-v6-runner.md, examples/ethers-v6/types/ethers-contracts/factories/Dai__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesInput__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesPure__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesView__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Events__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Issue428_Reproduction/A__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Issue428_Reproduction/B__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Library/Lib__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/LibraryConsumer__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Name-Mangling/NAME12mangling__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Overloads__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Payable/PayableFactory__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Payable/Payable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/ISimpleToken__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Issue552_Reproduction__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/KingOfTheHill/KingOfTheHill__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/KingOfTheHill/Withdrawable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/ERC721Enumerable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/ERC721__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721Enumerable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721Receiver__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/Rarity__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/SimpleToken__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/nested/a/NestedLibrary__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/nested/b/NestedLibrary__factory.ts, packages/target-ethers-v6/src/codegen/index.ts
Reverts dethcrypto/TypeChain#832
=> Revert "fix type ContractRunner"

.changeset/ethers-v6-runner.md, examples/ethers-v6/types/ethers-contracts/factories/Dai__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesInput__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesPure__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesView__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Events__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Issue428_Reproduction/A__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Issue428_Reproduction/B__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Library/Lib__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/LibraryConsumer__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Name-Mangling/NAME12mangling__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Overloads__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Payable/PayableFactory__factory.ts, packages/target-ethers-v6-test/types/factories/v0.6.4/Payable/Payable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/ISimpleToken__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Issue552_Reproduction__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/KingOfTheHill/KingOfTheHill__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/KingOfTheHill/Withdrawable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/ERC721Enumerable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/ERC721__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721Enumerable__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721Receiver__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/Rarity__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/SimpleToken__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/nested/a/NestedLibrary__factory.ts, packages/target-ethers-v6-test/types/factories/v0.8.9/nested/b/NestedLibrary__factory.ts, packages/target-ethers-v6/src/codegen/index.ts
Continuation of: https://github.com/dethcrypto/TypeChain/pull/832
=> Fix type ContractRunner

.changeset/ten-pants-learn.md, packages/typechain/src/utils/files/lowestCommonPath.ts, packages/typechain/test/utils/files/lowestCommonPath.test.ts
Runs CI on: https://github.com/dethcrypto/TypeChain/pull/773
=> Fix the `lowestCommonPath` function,  #772

.changeset/hungry-suits-check.md, packages/hardhat/src/config.ts, packages/hardhat/src/index.ts, packages/hardhat/src/types.ts
https://github.com/dethcrypto/TypeChain/pull/874
=> feat: add node16Modules flag for hardhat
