dethcrypto/TypeChain

lib/abiParser.ts
lib/cli.ts
package.json
scripts/test.sh
test/integration/ContractWithOverloads.spec.ts
test/integration/DumbContract.spec.ts
test/integration/Formatting.spec.ts
test/integration/utils/web3Contracts.ts
yarn.lock

Unfortunately I also had to update chalk to get it to build correctly.

switch to solcjs, fix formatting unit test, update chalk dependency

---

runtime/typechain-runtime.ts

- Typechain-runtime gets copied to the project
- If the linting rules don't match, you'd have to go into this file and add a tslint disable tag every time it's generated.

Disable tslint in typechain-runtime.ts

---

lib/generateSource.ts
test/integration/DumbContract.spec.ts
test/integration/contracts/DumbContract.sol

The fix here is simply to check what type the input argument is and special case arrays. Instead of just calling to string on the array, we map the values of the array to their string representation. I added an integration test for the case as well

Fix for https://github.com/Neufund/TypeChain/issues/39

---

lib/generateSource.ts
lib/typeParser.ts
test/integration/DumbContract.spec.ts
test/integration/contracts/DumbContract.sol

This change introduces a new `generateCodeForInputConversion` on the EvmType class which is used for converting from the input type to the type which web3 is expecting.

Fix for https://github.com/Neufund/TypeChain/issues/41 - Handle bytes as an input type

---

lib/typeParser.ts
test/integration/DumbContract.spec.ts
test/integration/contracts/DumbContract.sol

Hello Typechain team!
This pr fixes issues with #41 and also https://github.com/MARKETProtocol/types/issues/18
cc @eswarasai
I believe this fixes issues where a type definition is generated for a solidity function that accepts a `bytes32`  type argument.   We would love to get this included in a release as soon as possible, so if there is anything else needed here please let me know and I am happy to contribute. 
We just started using your package in our project, thank you for all you guys are doing!

added support for bytes32 as argument to solidity fx

---

lib/targets/web3/index.ts

Fixes bug with web3-1.0.0 target - Each generated definition file is written to "index.d.ts" so with multiple contracts each one overwrites the last as it is generated.

fix definition overwriting with web3-1.0.0 target

---

CHANGELOG.md
lib/targets/truffle/generation.ts
package.json
test/integration/targets/truffle/contracts/DumbContract.sol
test/integration/targets/truffle/migrations/1_initial_migration.ts
test/integration/targets/truffle/test/DumbContract.ts
yarn.lock

Closes: 
https://github.com/ethereum-ts/TypeChain/issues/113
https://github.com/ethereum-ts/TypeChain/issues/114
https://github.com/ethereum-ts/TypeChain/issues/115
Also, there were fixes to `truffle-typings` package.

added new fields from truffle-typings,  fix return data from tx creating calls

---

__snapshots__/DumbContract.spec.ts.js
lib/targets/legacy/generation.ts
scripts/test.sh
test/integration/contracts/DumbContract.sol
test/integration/targets/legacy/DumbContract.spec.ts

Fixes #120 
* updated code generation for passing boolean arguments in methods
* updated code generation for passing arrays, so nested boolean arguments work too
* updated tests for the legacy target, to verify that boolean values are passed correctly

[legacy] correctly pass boolean arguments in methods

---

lib/targets/web3/generation.ts
lib/targets/web3/index.ts
test/integration/targets/web3-1.0.0/DumbContract.spec.web3.ts
test/integration/targets/web3-1.0.0/package.json
test/integration/targets/web3-1.0.0/tsconfig.json
test/integration/targets/web3-1.0.0/web3.ts
test/integration/targets/web3-1.0.0/yarn.lock
tsconfig.json
tsconfig.production.json

Upgrade web3 to 1.0.0-beta.48

---

lib/targets/web3/generation.ts
lib/targets/web3/index.ts
test/integration/targets/web3-1.0.0/ContractWithOverloads.spec.web3.ts
test/integration/targets/web3-1.0.0/DumbContract.spec.web3.ts
test/integration/targets/web3-1.0.0/package.json
test/integration/targets/web3-1.0.0/web3.ts
test/integration/targets/web3-1.0.0/yarn.lock

Hey @krzkaczor , this is a great project! I had a go at improving the types for events, so that event listeners/event callbacks have properly typed params:
While I was at it, I updated the `web3` version; the biggest change here is probably the BigNumber change in web3: https://github.com/ethereum/web3.js/issues/2570 
**Changes**
* Upgrade the `web3-1.0.0` target's `web3` version to the latest beta (54)
* Adjust test setup and assertions to reflect `web3` changes
* Parse event inputs in order to improve the typing of contract events for the `web3-1.0.0` target
* Update existing types to reflect updated `web3` (e.g. `EstimateGasOptions`)
Let me know what you think. Cheers!

Improve event typing and update `web3` for the `web3-1.0.0` target

---

lib/targets/truffle/generation.ts
test/integration/targets/truffle/contracts/DumbContract.sol
test/integration/targets/truffle/test/DumbContract.ts

https://github.com/ethereum-ts/TypeChain/issues/104
I added call, sendTransaction and estimateGas methods to generation.ts for the truffle target
call returns the same output as sending the TX but no state changes are made
I checked the counter method after calling the simulated TX. 
I had to add another countup method to the smart contract which returned a uint to test the simulated return value.
sendTransaction returns the TX hash of the state changing method.
For this test I checked that the method returns a 66 length string.
estimateGas returns an integer showing how much gas the simulated TX would use.
For this test I checked that the estimated gas is over the minimum 20k threshold. Could also just check that it is an int

add non transacting transaction calls and tests to truffle target

---

lib/targets/ethers/generation.ts
test/integration/targets/ethers/ContractsWithStructs.spec.ts

Closes #119 
Added typings & tests for struct return types in ethers.js. Seems like this was simply missed for ethers, looks like all other targets already support struct return types

Add struct output types for ethers

---

lib/targets/ethers/generation.ts
lib/targets/ethers/index.ts

The `interface.functions.fnName.encode` methods that I added in PR #154 were effectively typed as, for example, `encode(params: [string, string, string]): string`. Though typesafe, this wasn't really helpful in developement.
With this change, I'm overriding not only the arguments typing for `encode`, but the whole method, and destructuring the arguments so their original names are shown, for example: `encode([receiverAddress, signature, assetData]: [string, string, string]): string`. I believe this is the best we can do here -- because ethers accepts the arguments as an array here, we can't just normally list the arguments with names.
Same problem solved for `encodeTopics` method on `interface.events.eventName`.
No functionality or typing is changed, only the names are added.

[ethers] named arguments for function args encoding methods

---

lib/targets/ethers/generation.ts
test/integration/targets/ethers/DumbContract.spec.ts

Closes #123 
I updated the generated typings for ethers, so that number and byte-array arguments accept precisely what do [the docs say](https://docs.ethers.io/ethers.js/html/api-contract.html#types) -- especially passing a `Buffer` for the binary `bytes/bytesN` types.
For a cleaner code I used the `BigNumberish` and `Arrayish` type unions exported by ethers, since that's exactly their job :) It results in better DX than `number | string | Buffer | UInt8Array`, which gets hard to read when you have 4 or more arugments to a contract function.
Updated the tests to check all the variants.

[ethers] fix argument types for bytes & numbers

---

__snapshots__/DumbContract.spec.ts.js
lib/parser/abiParser.spec.ts
lib/parser/abiParser.ts
lib/targets/ethers/generation.ts
lib/targets/ethers/index.ts
lib/targets/shared.ts
test/integration/before.ts
test/integration/contracts/DumbContract.sol
test/integration/targets/ethers/ContractWithOverloads.spec.ts
test/integration/targets/ethers/ContractsWithStructs.spec.ts
test/integration/targets/ethers/DumbContract.spec.ts
test/integration/targets/ethers/ethers.ts
test/integration/targets/legacy/DumbContract.spec.ts
test/integration/targets/web3-1.0.0/DumbContract.spec.web3.ts
test/integration/targets/web3-1.0.0/web3.ts
test/integration/utils/web3Contracts.ts

Fixes #137
ethers v5 beta doesn't look ready to be used yet, so I opted to solve #137 in TypeChain for the time being.
There are 2 options for this PR -- tell me what do you think.
(see only commit 11f380f)
In this variant, we keep the current behavior for ethers, where TypeChain only generates typings, with no runtime code whatsoever. This adds a simple `<ContractName>Factory` typing declaration, which helps to properly type constructor arguments for contract deployment -- but the ABI and bytecode must still be passed manually (usually re-reading the JSONs on disk).
(full PR)
In this variant, we deviate a bit from the current behavior: the contract typing files are left as they are now, but TypeChain also generates a separate runtime `<ContractName>Factory` class, which extends ethers' …

[ethers] Generate contract factories

---

__snapshots__/DumbContract.spec.ts.js
lib/targets/ethers/generation.spec.ts
lib/targets/ethers/generation.ts
lib/targets/ethers/index.ts
test/integration/contracts/DumbContract.sol
test/integration/targets/ethers/DumbContract.spec.ts

This is a follow-up for PR #160 (CC issue #137)
Problem: existing methods allowed only to deploy a new contract instance, or attach to an existing address, but only connecting through a complete `Signer` / `Wallet`. In actual use cases, you often don't need (or even _don't want_) the contract instance to have a signer connected, just a provider, to use contract's `view` or `pure` functions.
Proposed solution:
* add to the contract factories: `static connect(address: string, signerOrProvider: Signer | Provider)` -- this just invokes the `Contract` constructor with the same params and the hardcoded ABI (since we can't add runtime functions to our contract type declarations)
* for abstract contracts (or if bytecode was just not provided), generate a simplified version of the factory, …

[ethers] Factory for connecting to existing contract instances

---

lib/targets/ethers/generation.ts

The ethers.js library exposes the contract's methods at the root level
in addition to being stored within the "function" mapping. This simply
duplicates the same available methods from the function mapping to the
root of the contract instance to match the actual behaviour of the
library.

Add root level functions and constants for ethers

---

.gitignore
packages/core/lib/parser/abiParser.spec.ts
packages/core/lib/parser/abiParser.ts
packages/core/package.json
packages/typechain-target-ethers/lib/generation.spec.ts
packages/typechain-target-ethers/lib/generation.ts
packages/typechain-target-ethers/lib/index.ts
scripts/test.sh
test/integration/contracts/ContractWithLibrary.sol
test/integration/targets/ethers/ContractWithLibrary.spec.ts
yarn.lock

* closes #177 
* the parser also extracts references to unlinked libraries from the bytecode.
* if the contract json contains the `evm.bytecode.linkReferences` (which is the case e.g. when using [waffle](https://github.com/EthWorks/Waffle)), its contents are used to get human understandable keys for the library addresses object (ie. `contracts/file.sol:SomeContract` instead of a partial hash).
* the generated contract factory for `ethers` target will have another param to specify addresses of the libraries to be linked.
* other targets don't generate factories for now, but if they do, they will be able to use the updated parser `extractBytecode` function to easily implement similar linking feature.
* NOTE: the base for this PR is `kk/parser-rewrite` for easier review. It should be changed …

[ethers] link internal libraries in factory

---

packages/typechain-target-ethers/lib/index.ts
packages/typechain-target-truffle/lib/index.ts
packages/typechain-target-web3-v1/lib/index.ts

The previous implementation joined the user-provided outDir with the working
directory. This meant that an absolute path as an outDir would get concatenated
to the working dir. Using path.resolve instead handles both absolute and
relative paths properly.
```
> resolve(process.cwd(), '/foo')
'/foo'
> resolve(process.cwd(), 'foo')
'/home/spalladino/Projects/TypeChain/foo'
> resolve(process.cwd(), './foo')
'/home/spalladino/Projects/TypeChain/foo'
```

Handle absolute paths in outDir

---

packages/typechain-target-truffle/package.json

now
`warning " > typechain-target-truffle@1.0.1" has incorrect peer dependency "typechain@1.0.0^".`
Will not appar anymore, as the peerDependency is now specifying correct version

typechain-target-truffle: fixed peerDependency warning appearing during `yarn install`

---

packages/typechain-target-ethers/package.json

`warning " > typechain-target-ethers@1.0.2" has incorrect peer dependency "typechain@1.0.0^"`
now whould not appear anymore when using `yarn install`

 typechain-target-ethers: fixed peerDependency warning appearing during `yarn install`

---

packages/typechain-target-web3-v1/package.json

Now
`warning " > typechain-target-web3-v1@1.0.1" has incorrect peer dependency "typechain@1.0.0^".`
Will not appar anymore, as the peerDependency is now specifying correct version

typechain-target-web3-v1: fixed peerDependency warning appearing during `yarn install`

---

package.json
packages/typechain-target-web3-v1/lib/generation.ts
packages/typechain-target-web3-v1/lib/index.ts
packages/typechain-target-web3-v1/package.json
test/integration/targets/web3-v1/package.json
test/integration/targets/web3-v1/yarn.lock
yarn.lock

Fixes https://github.com/ethereum-ts/TypeChain/issues/187
Now, TC generated code uses web3 embedded types. There are no breaking changes for consumers.

upgrade web3, deal with breaking changes

---

packages/core/lib/parser/abiParser.ts

Tmp fix for: https://github.com/ethereum-ts/TypeChain/issues/209

do not throw on unrecognized ABI elements

---

packages/target-truffle-v4/src/codegen/headers.ts
packages/target-truffle-v5/src/codegen/headers.ts

As far as I can tell, Truffle's `artifacts.require` should use the `rawName` rather than the normalized `name`. e.g. a contract named `ERC20` won't be found when `require`d as `Erc20`.

Use raw names for `artifacts.require`

---

packages/target-truffle-v4-test/types/truffle-contracts/index.d.ts
packages/target-truffle-v4/src/codegen/headers.ts
packages/target-truffle-v5-test/types/truffle-contracts/index.d.ts
packages/target-truffle-v5/src/codegen/headers.ts

This PR changes the codegen for the Truffle artifact headers such that the contracts (and now, also contract instances) are exported and imported.
The use-case for this is the ease of importing multiple contracts from one location. I believe this was also the behaviour of TypeChain v1. Alternatively, this could also be done with a separate, optional file; but ideally this is done with TypeChain rather than in userland.
It seems as if the `no-unused-vars` eslint rule is violated in the generated files, so I'm not sure if there's a better solution here. `ts-generator` could also add `eslint-disable`, or maybe there's a neater solution.

Export contract types in artifact headers

---

packages/target-truffle-v4-test/types/truffle-contracts/types.d.ts
packages/target-truffle-v4/static/types.d.ts
packages/target-truffle-v5-test/types/truffle-contracts/types.d.ts
packages/target-truffle-v5/static/types.d.ts

`at()` is an asynchronous function that returns a promise.
v5: https://github.com/trufflesuite/truffle/blob/693b413f3507ca4cf0fb9c1cb02ef04665b3a945/packages/contract/lib/contract/constructorMethods.js#L60
v4: https://github.com/trufflesuite/truffle/blob/v4.1.17/packages/truffle-contract/contract.js#L427

Fix incorrect return type for contract.at()

---

README.md

With "ethers" set as the target instead of "ethers-v4", I was getting this error:
```
Error occured:  Couldn't find ethers. Tried loading: typechain-target-ethers, @typechain/ethers, /Users/paulrberg/Projects/Sablier/Magellan/Protocol/packages/contracts/ethers.
Perhaps you forgot to install typechain-target-ethers?
```
This PR fixes the commands in the README to refer to "ethers-v4" instead of "ethers", and it also comes with a few formatting enhancements.

docs: fix broken commands and examples

---

packages/target-truffle-v4-test/types/truffle-contracts/types.d.ts
packages/target-truffle-v4/static/types.d.ts
packages/target-truffle-v5-test/types/truffle-contracts/types.d.ts
packages/target-truffle-v5/static/types.d.ts

link() is used to link libraries to contracts.
```js
const mylib = await MyLib.new()
MyContract.link("MyLib", mylib.address)
const myContract = await MyContract.new()
```
Truffle v4:
https://github.com/trufflesuite/truffle/blob/v4.1.17/packages/truffle-contract/contract.js#L564
Truffle v5:
https://github.com/trufflesuite/truffle/blob/981e421e771aab4a018151093c5e40d3f1ec2176/packages/contract/lib/contract/constructorMethods.js#L157

Add link method to contract constructor

---

packages/target-ethers-v5/src/codegen/functions.ts

Before:
```typescript
callStatic: {
getValue(overrides?: CallOverrides): Promise<string>;
setValue(overrides?: Overrides): Promise<string>;
}
```
After:
```typescript
callStatic: {
getValue(overrides?: CallOverrides): Promise<string>;
setValue(overrides?: CallOverrides): Promise<string>;
}
```
In `CallOverrides` we can pass `from` property, which can be passed to non constant methods under `callStatic` bucket. Until now only constant methods were having the `CallOverrides` overrides. This PR fixes the specific case bug.
Testing: I've ran this PR in two of my projects with no breakings. However, to be more sure, can someone try in their project? It'd be great.

Fix callStatic overrides for non constant fns

---

packages/target-ethers-v5-test/types/Events.d.ts
packages/target-ethers-v5-test/types/Payable.d.ts
packages/target-ethers-v5/src/codegen/index.ts

This PR fixes a bug described in https://github.com/ethereum-ts/TypeChain/pull/258#issuecomment-660537576

Fix CallOverrides not imported

---

packages/target-ethers-v4-test/test/Overload.test.ts
packages/target-ethers-v4-test/types/DataTypesInput.d.ts
packages/target-ethers-v4-test/types/DataTypesPure.d.ts
packages/target-ethers-v4-test/types/DataTypesView.d.ts
packages/target-ethers-v4-test/types/Events.d.ts
packages/target-ethers-v4-test/types/NameMangling.d.ts
packages/target-ethers-v4-test/types/Overloads.d.ts
packages/target-ethers-v4-test/types/Payable.d.ts
packages/target-ethers-v4-test/types/index.d.ts
packages/target-ethers-v4/src/codegen/functions.ts
packages/target-ethers-v4/src/codegen/index.ts
packages/target-ethers-v4/src/codegen/types.ts
packages/target-ethers-v4/static/index.d.ts

Similar to https://github.com/ethereum-ts/TypeChain/pull/254 - this fixes the situation to provide override arguments as specified.  
There are a few specifics that are considered here:
- According to [the documentation](https://docs.ethers.io/v4/api-contract.html#overrides) for ethers v4 (and my own experience where i needed these overrides), **every** method has overrides available to it.  Their example only shows a few properties but when looking at the v5 types they are defined extending the transaciton overrides while adding a `from` key (and `blockTag` which im not sure, i didnt add that). 
- I did not add the differentiation that the `target-ethers-v5` has where it checks if the fn is a constant function - this is due to the fact that it seemed to be doing some extra changes to …

Fix target-ethers-v4 to allow transaction and contract call overrides 

---

packages/target-ethers-v5/src/codegen/index.ts
packages/target-ethers-v5/src/index.ts

#278
Before:
```
<Contract>.d.ts
<Contract>Factory.ts
```
Only Factory file was exported
After:
```
<Contract>.ts
<Contract>Factory.ts
```
Now both the ts files are exported from `index.ts`
I've tried this PR on my current project, and didn't get any breakings. Though it can be tried on multiple projects to be sure.

[ethers-v5] Export contract types in index.ts

---

packages/typechain/src/parser/normalizeName.ts

The enforced camel casing breaks existing standard names like `ERC20.sol` and make the typings look like `Erc20.d.ts`, which adds complexity and confusion and requires unnecessary work to use typechain@2.0.

Don't enforce camel case

---

.changeset/smart-ants-begin.md
contracts/Name-Mangling.sol
packages/target-ethers-v4-test/types/NameMangling.d.ts
packages/target-ethers-v4-test/types/factories/NameMangling__factory.ts
packages/target-ethers-v4/src/codegen/index.ts
packages/target-ethers-v4/src/codegen/reserved-keywords.ts
packages/target-ethers-v5-test/types/NameMangling.d.ts
packages/target-ethers-v5-test/types/factories/NameMangling__factory.ts
packages/target-ethers-v5/src/codegen/index.ts
packages/target-ethers-v5/src/codegen/reserved-keywords.ts
packages/target-truffle-v4-test/types/truffle-contracts/NAME12mangling.d.ts
packages/target-truffle-v5-test/types/truffle-contracts/NAME12mangling.d.ts
packages/target-web3-v1-test/types/Name-Mangling.d.ts

Closes: https://github.com/ethereum-ts/TypeChain/issues/298

[ethers-v4/5] Respect reserved keywords while generating top-level typings

---

.changeset/shaggy-schools-poke.md
.gitignore
packages/target-web3-v1-test/test/DataTypesInput.test.ts
packages/target-web3-v1-test/types/DataTypesInput.d.ts
packages/target-web3-v1-test/types/Library.d.ts
packages/target-web3-v1-test/types/LibraryConsumer.d.ts
packages/target-web3-v1-test/types/Overloads.d.ts
packages/target-web3-v1-test/types/types.d.ts
packages/target-web3-v1/src/codegen/types.ts
packages/target-web3-v1/static/types.d.ts

web3 can handle BN values for number inputs.
This PR adds ` | BN` to all number inputs, making working with web3 + TypeScript easier.
Instead of `contract.methods.foo(bn.toString())`
we can now just `contract.methods.foo(bn)`.
There is a runtime error when passing BN as properties of structs or arrays:
```
Error: invalid number value (arg="input1", coderType="uint8", value="1")
at Object.throwError (/TypeChain/node_modules/ethers/utils/errors.js:68:17)
at CoderNumber.encode (/TypeChain/node_modules/ethers/utils/abi-coder.js:353:20)
at /TypeChain/node_modules/ethers/utils/abi-coder.js:605:59
at Array.forEach (<anonymous>)
...
```
This appears to be a bug in `web3-eth-contract`'s `abi-coder`, which under the hood, [uses `ethers`'s `abi-coder`](https://github.com/ChainSafe/web3.js/blob/1.x/pa …

[web3] accept BN as input for numbers

---

packages/hardhat/README.md

The old way only works when upgrading and not clearing out your npm_modules (as the old package is still installed)

docs: use @typechain/hardhat in hardhat.config.ts

---

packages/target-ethers-v5-test/test/Events.test.ts
packages/target-ethers-v5-test/types/Events.d.ts
packages/target-ethers-v5/src/codegen/index.ts

#379
Before:
```ts
Transfer(
from: string | null,
to: string | null,
value: null
): TypedEventFilter<
[string, string, BigNumber],
{ from: string; to: string; amount: BigNumber; }
>;
// for all erc20 transfers
const filter = contract.filters.Transfer(null, null, null)
```
After
```ts
Transfer(
from?: string | null,
to?: string | null,
value?: null
): TypedEventFilter<
[string, string, BigNumber],
{ from: string; to: string; amount: BigNumber; }
>;
// for all erc20 transfers
const filter = contract.filters.Transfer()
// for all erc20 transfers from a given address 0x1234...
const filter = contract.filters.Transfer('0x1234...')
// for all erc20 transfers to a given address 0x1234...
const filter = contract.filters.Transfer(null, '0x1234...')
```

[ethers-v5] Make filter parameters optional

---

README.md

It is better to add it since user might think `ethers-v5` is not supported.

update README with ethers-v5

---

packages/hardhat/src/constants.ts
packages/hardhat/src/index.ts

I'm building a plugin that depends on `@typechain/hardhat`, and I'd like to be able to import the name of the TypeChain task from the package. Currently the "typechain" task is named via a constant literal.
Besides this being useful for my own purposes, defining task names as constants in a `constants.ts` file seems to be the standard used by Hardhat in their native plugins:
https://github.com/nomiclabs/hardhat/blob/88ab5f0b7bdcffe8627f86e020846f056be3bf20/packages/hardhat-etherscan/src/constants.ts

feat: define TASK_TYPECHAIN constant

---

packages/hardhat/src/index.ts

This at least partially fixes the issue described in #420. The `HardhatPluginError` import was unused so I removed that, and added the `./type-extensions` import to make sure it's included in the resulting `index.d.ts`.

Import type-extensions in Hardhat plugin index

---

.changeset/stupid-eggs-hunt.md
packages/hardhat/src/constants.ts
packages/hardhat/src/index.ts

Using a subtask affords more flexibility to plugin developers and end users who wish to integrate with Typechain.  I have a case where bytecode needs to be modified after compilation, but before types are generated, and currently the only means of doing this relies on importing tasks in a particular order, which is not intuitive.

Move Hardhat type generation to subtask

---

packages/hardhat/package.json

See https://github.com/nomiclabs/hardhat/issues/1672, specifically https://github.com/nomiclabs/hardhat/issues/1672#issuecomment-894497156
See also https://github.com/sc-forks/solidity-coverage/issues/644

Sync hardhat's peer dependency to latest typechain

---

.changeset/good-starfishes-appear.md
packages/hardhat/test/fixture-projects/hardhat-project/typechain/ERC20.d.ts
packages/target-ethers-v5-test/test/Events.test.ts
packages/target-ethers-v5-test/types/Events.d.ts
packages/target-ethers-v5/src/codegen/index.ts

Usage
```ts
import type { Transfer_TypedEvent } from '../typechain/MyErc20Token';
// overloaded events
import type { Execute_bytes32_TypedEvent, Execute_address_bytes_TypedEvent } from '../typechain/MyMultisig';
// ...
const parsed = contract.interface.parseLog(log) as TransferEvent;
parsed.args.from // string
parsed.args.to // string
parsed.args.value // BigNumber
```
#440

[ethers-v5] Generate and export typed events

---

packages/hardhat/README.md

The sample tsconfig.json was missing the hardhat folder, possibly making it confusing for people expecting:
- **Frictionless** - return type of `ethers.getContractFactory` will be typed properly - no need for casts
Fixes #460

hardhat: include typechain in sample tsconfig.json

---

.changeset/unlucky-ties-beg.md
packages/hardhat/test/fixture-projects/hardhat-project/typechain/hardhat.d.ts
packages/target-ethers-v5/src/codegen/hardhat.ts

The PR https://github.com/dethcrypto/TypeChain/pull/473 introduced a bug that the getContractAt returns a factory type. But it should return a contract type instead. This PR aims to fix this.

[ethers-v5] fix for getContractAt incorrect type

---

.eslintrc.js
tsconfig.json

I started to work on Windows issues and I noticed ESLint is panicking in JS files, because they're not included in the _tsconfig.json_.
It could safely be disregarded, but since a red squiggly line looks the same as a type error in my IDE, I decided it won't hurt to fix it.
Noticing that the project uses _tsconfig.json_ files for development and _tsconfig.build.json_ files for production builds, I added JS files to the root _tsconfig.json_. I considered adding a new file — _tsconfig.eslint.json_ — but if this change to _tsconfig.json_ doesn't break anything I suppose it's better to keep it minimal.
However, led me to another problem — I expect this one happens because I'm on Windows.
```
❯ yarn eslint ./.eslintrc.js
D:\workspace\TypeChain\.eslintrc.js
0:1  error  The package.json file …
```

Include *.js files in tsconfig.json for ESLint

---

packages/typechain/package.json

The peer dependency on typescript is required to satisfy the peer dependency requirements of ts-essentials.
Adding the peer dependency eliminates a warning in our build which uses typechain.
Thanks for a great tool!

typechain: Add missing peer dependency on typescript

---

.changeset/silver-foxes-remember.md
packages/typechain/src/parser/parseEvmType.ts
packages/typechain/test/parser/parseEvmType.test.ts

I think this is only relevant for ethers-v5 - I had an error with it and my function that returns Struct[][]

Fix structName for nested array of struct

---

.changeset/five-files-rest.md
packages/typechain/package.json
packages/typechain/src/cli/parseArgs.ts
packages/typechain/test/cli/parseArgs.test.ts
yarn.lock

Closes https://github.com/dethcrypto/TypeChain/issues/558
_The message itself:._
```
TypeChain/packages/typechain on  cli-help [$] is 📦 v6.0.5 via  v14.17.0 
❯ node dist/cli/cli -h
TypeChain generates TypeScript types for Ethereum contract ABIs.
Thank you for using it!
Options
--glob string[]                Pattern that will be used to find ABIs. Remember about adding     
quotes: typechain "**/*.json", examples: ./abis/**/*.abi,
./abis/?(Oasis.abi|OasisHelper.abi).
--target string                One of ethers-v4, ethers-v5, truffle-v4, truffle-v5, web3-v1 or   
path to your custom target. Typechain will try to load package    
named: @typechain/<target>, so make sure that desired package is  
installed.
--out-dir string               Output directory for generated files. …
```

Show help message given `-h` flag

---

.eslintrc.js

POV:
1. You import a thing.
2. You save the file.
3. The import declaration you just wrote dissapears.
---
`unused-imports/no-unused-imports-ts` is an evil rule to run inside of a text editor. I've been trying to live with it for two months, but enough is enough :P What's worse, I have autosave enabled, so I import a thing, wait a second and it dissapears :>
`VSCODE_PID` is not set when we run ESLint from the CLI so unused imports will be safely removed in `yarn test:fix`.

Disable no-unused-import-ts ESLint rule if running inside VSCode

---

.changeset/pretty-waves-leave.md
contracts/v0.6.4/DataTypesInput.sol
package.json
packages/hardhat-test/typechain-types/Demo.ts
packages/hardhat-test/typechain-types/factories/Demo__factory.ts
packages/target-ethers-v4-test/types/DataTypesInput.d.ts
packages/target-ethers-v4-test/types/factories/DataTypesInput__factory.ts
packages/target-ethers-v5-test/test/DataTypesInput.test.ts
packages/target-ethers-v5-test/test/Issue552Reproduction.test.ts
packages/target-ethers-v5-test/types/DataTypesInput.ts
packages/target-ethers-v5-test/types/DataTypesPure.ts
packages/target-ethers-v5-test/types/DataTypesView.ts
packages/target-ethers-v5-test/types/Events.ts
packages/target-ethers-v5-test/types/Issue552Reproduction.ts
packages/target-ethers-v5-test/types/KingOfTheHill.ts
packages/target-ethers-v5-test/types/factories/DataTypesInput__factory.ts
packages/target-ethers-v5/src/codegen/index.ts
packages/target-ethers-v5/src/codegen/structs.ts
packages/target-ethers-v5/src/codegen/types.ts
packages/target-ethers-v5/test/structs.test.ts
packages/target-truffle-v5-test/types/truffle-contracts/DataTypesInput.d.ts
packages/target-web3-v1-test/types/DataTypesInput.ts
packages/typechain/src/parser/abiParser.ts
packages/typechain/src/parser/parseEvmType.ts
packages/typechain/test/parser/parseEvmType.test.ts
yarn.lock

```solidity
contract MyContract
function input_multiple_structs_with_same_name(StructsLib1.Info memory info1) public pure returns (StructsLib2.Info memory info2) {
info2.a = address(info1.a);
info2.b = address(info1.b);
}
}
library StructsLib1 {
struct Info {
uint160 a;
uint160 b;
}
}
library StructsLib2 {
struct Info {
address a;
address b;
}
}
```
Generated Typings:
```typescript
export type InfoStruct = { a: BigNumberish; b: BigNumberish };
export type InfoStructOutput = [BigNumber, BigNumber] & {
a: BigNumber;
b: BigNumber;
};
input_multiple_structs_with_same_name(
info1: InfoStruct,
overrides?: CallOverrides
): Promise<InfoStructOutput>;
```
---
Closes #574

Multiple struct inputs with same name

---

.changeset/rich-penguins-shave.md
packages/hardhat/src/constants.ts

The Hardhat internal tasks use colons rather than hyphens to simulate task namespaces: https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/builtin-tasks/task-names.ts.  TypeChain should do the same.  Change should not be considered breaking because the proper way to reference a task name is by importing `constants.ts`.

update internal task name to match hardhat convention

---

packages/hardhat/README.md

Since newer versions of typechain default to `./typechain-types` for the type outputs I think the README should match the default as it easily confuses new users.

Fix sample tsconfig.json excerpt in README.md

---

.changeset/four-carrots-collect.md
packages/typechain/src/parser/abiParser.ts
packages/typechain/test/parser/abiParser.test.ts

Adds tests to @joeandrews' PR (https://github.com/dethcrypto/TypeChain/pull/618) and applies his change.
From @joeandrews' PR:
Forge / Foundry structures ABI's as below. This change makes the ABI parser compatible with the output from forge.
```
{
"abi": [],
"bytecode": {
"object": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212205bf70e5aa6eb164145ba1ab154b06c77bba3192b4507a03c711393334ab8aafb64736f6c634300080a0033",
"sourceMap": "153:195:3:-:0;;;;;;;;;;;;;;;-1:-1:-1;;;153:195:3;;;;;;;;;;;;;;;;;",
"linkReferences": {}
},
"deployed_bytecode": {
"object": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212205 …
```

Update abiParser.ts to work with foundry / forge output + Tests

---

packages/target-truffle-v5-test/package.json

This is needed to compile contracts in nested directories. We missed it because we commit generated types.

Add missing --all flag to truffle-v5-test truffle call

---

packages/target-ethers-v5/package.json
packages/target-ethers-v5/src/index.ts
packages/target-ethers-v5/test/typescript-version.test.ts
pnpm-lock.yaml

Crash Ethers V5 target if TS version < 4.3

---

README.md

At this moment our readme says:
> _TypeChain_
> _TypeChain_
After this change, there's only one _TypeChain_, the one in the image (and its alt text).

Write TypeChain just once

---

examples/truffle-v5/migrations-ts/1_initial_migration.ts
examples/truffle-v5/migrations-ts/2_deploy_contracts.ts

Migration functions in the truffle-v5 example are cast, thus providing on type safety nor autocompletion. In the following, `deployer` has type `any`:
```ts
module.exports = function (deployer) {
deployer.deploy(Migrations)
} as Truffle.Migration
```
This PR changes to a slightly longer format where `deployer`'s type is recognized as `Truffle.Deployer`:
```ts
const migration: Truffle.Migration = (deployer) => {
deployer.deploy(Migrations);
};
module.exports = migration;
```

Type migration in truffle-v5 example

---

.changeset/light-hairs-chew.md
packages/hardhat/package.json
packages/hardhat/src/index.ts
pnpm-lock.yaml

Hey @krzkaczor,
Just a quick PR optimizing this plugin. This makes projects using it run faster in general. You can appreciate the difference if you run a `npx hardhat --help` in a project using this version of the plugin and `latest`.
The difference is not huge, but it compounds with other plugins, so I'm doing this for every plugin included in the hardhat toolbox.
Also, I don't think lodash is needed anymore, so I removed it.

[Hardhat plugin] Don't import libraries until they are needed

---

.changeset/fast-hornets-trade.md
packages/typechain/src/typechain/runTypeChain.ts

Skip typechain run if all ABIs in a project are empty (which can occur if the project has a single empty contract).
Fixes #717
Fixes #728

Skip run if project has no ABIs

---

.changeset/pink-ads-rhyme.md
packages/target-web3-v1-test/types/v0.6.4/DataTypesInput.ts
packages/target-web3-v1-test/types/v0.6.4/DataTypesPure.ts
packages/target-web3-v1-test/types/v0.6.4/DataTypesView.ts
packages/target-web3-v1-test/types/v0.6.4/Events.ts
packages/target-web3-v1-test/types/v0.8.9/Issue552_Reproduction.ts
packages/target-web3-v1-test/types/v0.8.9/KingOfTheHill/KingOfTheHill.ts
packages/target-web3-v1-test/types/v0.8.9/Rarity/Rarity.ts
packages/target-web3-v1/src/codegen/events.ts
packages/target-web3-v1/src/codegen/functions.ts
packages/target-web3-v1/src/codegen/index.ts
packages/target-web3-v1/src/codegen/structs.ts
packages/target-web3-v1/src/codegen/types.ts
packages/target-web3-v1/src/common.ts
packages/target-web3-v1/src/index.ts

This PR adds support for struct parsing to @typechain/web3-v1, similarly to @typechain/ethers-v5.
Target from this PR is on [NPM ](https://www.npmjs.com/package/typechain-target-web3-v1-3mihai3) if you want to try it out

Add struct parsing to @typechain/web3-v1

---

.changeset/funny-cobras-invent.md
packages/target-ethers-v5/package.json

Fixes #822. No changeset added since it will not cause an immediate version bump.

Remove obsolete peer dependency `@ethersproject/bytes@^5.0.0` from `target-ethers-v5`

---

.changeset/ethers-v6-runner.md
examples/ethers-v6/types/ethers-contracts/factories/Dai__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesInput__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesPure__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesView__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Events__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Issue428_Reproduction/A__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Issue428_Reproduction/B__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Library/Lib__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/LibraryConsumer__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Name-Mangling/NAME12mangling__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Overloads__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Payable/PayableFactory__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Payable/Payable__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/ISimpleToken__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Issue552_Reproduction__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/KingOfTheHill/KingOfTheHill__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/KingOfTheHill/Withdrawable__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/ERC721Enumerable__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/ERC721__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721Enumerable__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721Receiver__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/IERC721__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/Rarity/Rarity__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/SimpleToken__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/nested/a/NestedLibrary__factory.ts
packages/target-ethers-v6-test/types/factories/v0.8.9/nested/b/NestedLibrary__factory.ts
packages/target-ethers-v6/src/codegen/index.ts

fix type ContractRunner

---

.changeset/lazy-eggs-brush.md
examples/ethers-v5-nodenext/types/ethers-contracts/index.ts
packages/typechain/src/codegen/createBarrelFiles.ts

This adds a proper suffix to directory imports as well (as long as they are actual files and not types).
This should close #819.

Add directory exports module suffix

---

.changeset/three-schools-peel.md
contracts/v0.6.4/DataTypesInput.sol
contracts/v0.6.4/Events.sol
packages/target-ethers-v5-test/test/DataTypesInput.test.ts
packages/target-ethers-v5-test/test/Events.test.ts
packages/target-ethers-v5-test/types/factories/v0.6.4/DataTypesInput__factory.ts
packages/target-ethers-v5-test/types/factories/v0.6.4/Events__factory.ts
packages/target-ethers-v5-test/types/v0.6.4/DataTypesInput.ts
packages/target-ethers-v5-test/types/v0.6.4/Events.ts
packages/target-ethers-v5-test/types/v0.8.9/KingOfTheHill/KingOfTheHill.ts
packages/target-ethers-v5/src/codegen/events.ts
packages/target-ethers-v6-test/test/Events.test.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/DataTypesInput__factory.ts
packages/target-ethers-v6-test/types/factories/v0.6.4/Events__factory.ts
packages/target-ethers-v6-test/types/v0.6.4/DataTypesInput.ts
packages/target-ethers-v6-test/types/v0.6.4/Events.ts
packages/target-truffle-v5-test/types/truffle-contracts/DataTypesInput.d.ts
packages/target-truffle-v5-test/types/truffle-contracts/Events.d.ts
packages/target-web3-v1-test/types/v0.6.4/DataTypesInput.ts
packages/target-web3-v1-test/types/v0.6.4/Events.ts
packages/typechain/src/utils/signatures.ts

Expands on https://github.com/dethcrypto/TypeChain/pull/488 to add the some functionality for events. 
Fixes https://github.com/dethcrypto/TypeChain/issues/785 and https://github.com/dethcrypto/TypeChain/issues/433 which might have been a regression. 
Added a bit more tests, also added a test to `ethers-v6` to make sure it already works as expected.

[ethers-v5] Fix event and function signatures with tuples and array of tuples

---

.changeset/moody-lamps-mix.md
examples/ethers-v6-nodenext/types/ethers-contracts/common.ts
examples/ethers-v6/types/ethers-contracts/common.ts
packages/hardhat-test/typechain-types/common.ts
packages/hardhat/test/fixture-projects/hardhat-project/typechain-types/common.ts
packages/target-ethers-v6-test/test/Payable.test.ts
packages/target-ethers-v6-test/types/common.ts
packages/target-ethers-v6/static/common.ts

Supersedes: https://github.com/dethcrypto/TypeChain/pull/818

fix: always use view overrides for statcCalls
